import { Inter } from 'next/font/google';

import GoogleAnalytics from '@/components/google-analytics';
import { Toaster } from '@/components/ui/sonner';
import { ENV_LOCALE } from '@/constants/env';

import Providers from './providers';

import type { Metadata } from 'next';

import './globals.css';

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-inter'
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang={ENV_LOCALE}>
			<body className={`${inter.variable} font-sans`}>
				<Providers>
					<Toaster richColors position="top-center" />
					{children}
				</Providers>
			</body>
			<GoogleAnalytics />
		</html>
	);
}
